#//////////////////////////////////////////////////////////////////////#
#	_docker-compose.yml                                                #
#//////////////////////////////////////////////////////////////////////#

networks:
    smironet:
        name: smironet
        diver: bridge

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        port:
         - 443:443
        volumes:
         - wordpress_data:/var/www/html
        restart: always
        networks:
         - smironet

    mariadb:
         container_name: mariadb
         build: ./requirements/mariadb
         volumes:
          - mariadb_data:/var/lib/mysql
         restart: always
         networks:
          - smironet
         env_file:
          - .env

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        volumes:
         - wordpress_data:/var/www/html
        restart: always
        networks:
         - smironet
        env_file:
          - .env

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            device: /home/smiro/data/mysql
            o: bind

    wordpress_data:
        driver: local
        driver_opts:
            type: none
            device: /home/smiro/data/wordpress
            o: bind
